package dev.yort

import kotlin.test.Test
import org.junit.jupiter.api.Assertions.assertEquals

class Day07Test {

    @Test
    fun simplest() {
        val lines = """
            .S.
            ...
        """.trimIndent().lines()
        val grid = parseGrid(lines)
        val start = findGridEntry(grid = grid, value = 'S')
        val timelines = Day07.traceParticle(start.key, grid)
        assertEquals(1, timelines)
    }

    @Test
    fun simpleSplit() {
        val lines = """
            .S.
            .^.
            ...
        """.trimIndent().lines()
        val grid = parseGrid(lines)
        val start = findGridEntry(grid = grid, value = 'S')
        val timelines = Day07.traceParticle(start.key, grid)
        assertEquals(2, timelines)
    }

    @Test
    fun fullPart2Example() {
        val lines = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
        """.trimIndent().lines()
        val grid = parseGrid(lines)
        val start = findGridEntry(grid = grid, value = 'S')
        val timelines = Day07.traceParticle(start.key, grid)
        assertEquals(40, timelines)
    }

    @Test
    fun find() {
        val lines = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .......^.......
            ...............
        """.trimIndent().lines()
        val grid = parseGrid(lines)
        val start = findGridEntry(grid = grid, value = 'S')
        val timelines = Day07.traceParticle(start.key, grid)
        assertEquals(6, timelines)
    }

}
